"""
Quick summary of test users
"""

print("=" * 80)
print("TEST USER CREDENTIALS FOR MIRAKLE PLATFORM")
print("=" * 80)
print()
print("ADMIN USER:")
print("  Email: admin@test.com")
print("  Password: admin123")
print("  Login at: http://localhost:5000/admin_login.html")
print()
print("STARTUP USER:")
print("  Email: startup@test.com")
print("  Password: startup123")
print("  Login at: http://localhost:5000/login.html")
print()
print("CORPORATE USER:")
print("  Email: corporate@test.com")
print("  Password: corporate123")
print("  Login at: http://localhost:5000/login.html")
print()
print("ENABLER USER:")
print("  Email: enabler@test.com")
print("  Password: enabler123")
print("  Login at: http://localhost:5000/login.html")
print()
print("=" * 80)
print()
print("To test the platform:")
print("1. Make sure the server is running: python app.py")
print("2. Open http://localhost:5000 in your browser")
print("3. Use any of the credentials above to login")
print("4. Check the admin dashboard with admin credentials")
print()
print("=" * 80)
